---
title: "Self-learning - Spatial Transcriptomics"
sidebar: false
toc: false
---

## Learning Objectives

- Experimental design best practices of current spatial transcriptomics technologies
- Data loading and quality control of Visium HD samples
- Standard single-cell workflows adapted for spatial data, including highly variable gene selection, PCA, UMAP, kNN, and clustering
- Cell type annotation with deconvolution using `RCTD` for sequencing-based technologies
- Spatial-specific analyses that utilize the physical location of bins/cells on the tissue, including:
   - Spatial clustering with `BANKSY`
   - Spatially variable gene detection with Moran's I
   - Cell-cell communication with `CellChat`


## Installations

Follow the [installation instructions](https://hbctraining.github.io/Intro-to-spatial-transcriptomics/#installation-requirements) on the main page.

## Lessons

### Part 1: Pre-reading

1.  [Spatial Technology Overview](../lessons/01_spatial_technologies.qmd)
2.  [Space Ranger Summary](../lessons/02_spaceranger.qmd)

### Part 2: Set-up and QC

3.  [Load Visium HD Data](../lessons/03_loading_spatial_data.qmd)
4.  [Theory of PCA](../lessons/04_theory_of_PCA.qmd)
5.  [Quality Control](../lessons/05_quality_control.qmd)

### Part 3: scRNA-seq workflow

6.  [Normalization and Sketch Downsampling](../lessons/06_normalization_and_sketch.qmd)
7.  [Dimensionality Reduction](../lessons/07_dim_reduction.qmd)
8.  [Clustering](../lessons/08_clustering.qmd)
9.  [Integration](../lessons/09_integration.qmd)
10. [Seurat Cheatsheet](../lessons/10_seurat_cheatsheet.qmd)

### Part 4: Spatial and coordinate-based analyses

11. [BANKSY Spatial Clustering](../lessons/11_banksy_clustering.qmd)
12. [Deconvolution](../lessons/12_deconvolution.qmd)
13. [Differential Expression and Pathway Analysis](../lessons/13_dge_pathway.qmd)
14. [Spatially Variable Genes](../lessons/14_svgs.qmd)
15. [Cell-Cell Communication](../lessons/15_cellchat.qmd)

## Resources